name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - master
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
    - name: Checkout base code
      uses: actions/checkout@v2
    - name: Checkout wiki code
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: wiki-repo
    - uses: OrlovM/Wiki-Actionv0.1.1
      with:
        path: 'wiki'

