name: Update Wiki

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  updateWiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          path: base-code
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki 
      - name: Push to wiki
        run: |
          cd wiki
          echo `cat Home.md`
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add changes" && git push
