name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - master
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
    - name: Checkout base code
      uses: actions/checkout@v2
    - uses: OrlovM/Wiki-Action@v0.1.7
      with:
        path: 'wiki'

