name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - master
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
    - uses: ./OrlovM/Wiki-Action@v0.1.1
      with:
        path: 'wiki'
